apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  selector:
    app: blog-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
