---
- name: restart node exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted